---
- hosts: omnibox
  remote_user: root
  gather_facts: no
  pre_tasks:
    - name: 'install python2'
      raw: sudo apt-get -y install python-simplejson

    - name: install apt requirements
      apt: pkg=aptitude

    - name: update pre-installed packages
      apt: upgrade=full update_cache=yes

- hosts: omnibox
  user: root

  vars_files:
    - "{{tape_dir}}/vars/defaults.yml"
    - tape_vars.yml

  roles:
    - general
    - ufw
    - deployer_user
    - frontend_install_essentials
    - monit_install
    - mongodb
    - nginx
    - frontend_deploy
    - node_api_configure
    - letsencrypt
    - monit_activate # Run Last
